development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgressql
  encoding: unicode
  database: db/production.postgressql
  pool: 5
  timeout: 5000
  username: user
  password: user
